In [1]:
pip install numpy

Note: you may need to restart the kernel to use updated packages.



[notice] A new release of pip is available: 25.1.1 -> 25.2
[notice] To update, run: python.exe -m pip install --upgrade pip


In [2]:
import numpy as np

In [11]:
s = np.array(5)
# print(s.shape)
v= np.array([1,2,3])
m=np.array([[1,2,3],
            [4,5,6],
            [7,8,9]])
print(v.ndim)
print(v.shape)


1
(3,)


In [4]:
vec_1=np.array([1,2,3,4,5,6])
mat_1=vec_1.reshape(3,2)
print(vec_1)
print(mat_1)


[1 2 3 4 5 6]
[[1 2]
 [3 4]
 [5 6]]


In [5]:
vec_2=np.array([1,2,3,4])
mat_2=vec_2.reshape((vec_2.shape[0],1))
mat_2
vec_2[3]

np.int64(4)

In [15]:
vec_2.shape[0]

4

In [27]:
vec_2[:,None]
vec_2[:None]
vec_2[1:3]

array([2, 3])

In [28]:
mat=np.array([[1,0.2,3],
              [4,True,6],
              [7,8,9]
    
])
mat.dtype
mat[1,2]
mat[1:3,0:2]

array([[4., 1.],
       [7., 8.]])

In [ ]:
class A:
    x=3
    o1=

In [29]:
transpose_arr=mat.T
transpose_arr

array([[1. , 4. , 7. ],
       [0.2, 1. , 8. ],
       [3. , 6. , 9. ]])

In [31]:
mat=np.zeros((3,4))
mat

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [32]:
mat=np.identity(3,,dtype='float32')
mat

SyntaxError: invalid syntax (3238672960.py, line 1)

In [6]:
np.savez('test.npz',ones_mat=mat_1,zero_mat=mat_2)

In [8]:
with np.load('test.npz') as file:
    mat_1=file['ones_mat']
    mat_2=file['zero_mat']
mat_1

array([[1, 2],
       [3, 4],
       [5, 6]])

In [10]:
m1=np.array([[4,7,8],
             [0,0,0]])

m2=np.array([[2,5,9],
             [1,1,1]])

vert_mat=np.vstack((m1,m2))
vert_mat

array([[4, 7, 8],
       [0, 0, 0],
       [2, 5, 9],
       [1, 1, 1]])

In [11]:
m1=np.array([[4,7,8],
             [0,0,0]])

m2=np.array([[2,5,9],
             [1,1,1]])

vert_mat=np.hstack((m1,m2))
vert_mat

array([[4, 7, 8, 2, 5, 9],
       [0, 0, 0, 1, 1, 1]])

In [12]:
s=4
v=np.array([2,4,1,7,6])
v==s

array([False,  True, False, False, False])

In [13]:
v=np.array([2,4,1,7,6])
np.any(v>3)

np.True_

In [14]:
v1=np.array([2,4,1,7,6])
v2=np.array([1,5,1,9,7])
np.isclose(v1,v2,atol=1)


array([ True,  True,  True, False,  True])

In [15]:
v=np.array([2,4,1,7,6])
condition= v>=4
cond_access =v[condition]
print(cond_access)

[4 7 6]
